<script lang="ts">
  /**
   * The sheet, previewed at a size you can read and enlarged when you cannot.
   *
   * ── Why this is its own component ──────────────────────────────────
   *
   * `DetailingWorkflow` crossed the 600-line ceiling the suite enforces the moment the enlarge
   * dialog landed in it, and the boundary was obvious: everything here is about ONE drawing —
   * which sheet it is, how big it is shown, and how to see it properly. The workflow around it is
   * about assemblies, conflicts, review and exports.
   *
   * ── One projection, two presentations ──────────────────────────────
   *
   * Both the preview and the dialog render `detailingStore.sheetSvg`. There is no second renderer
   * and no separate geometry: what you enlarge is exactly what the DXF and the report carry, which
   * is the whole reason the drawing is trustworthy at all.
   *
   * The scroll IS the pan. The SVG keeps its natural size inside a scrolling box rather than being
   * fitted to the window, because a 1:50 elevation scaled down to a panel column is not a smaller
   * drawing, it is an unreadable one — which is what the preview used to be.
   */
  import { t, tp } from '../../../lib/i18n';
  import { detailingStore } from '../../../lib/store/detailing.svelte';
  import { captureFocus, cycleTabWithin } from '../../../lib/utils/dialog-focus';

  interface Props {
    /** The assembly the sheet belongs to, for the caption. */
    assemblyLabel: string;
  }
  const { assemblyLabel }: Props = $props();

  let sheetOpen = $state(false);
  let sheetDialog = $state<HTMLDivElement | null>(null);

  const kindLabel = $derived(detailingStore.sheetKind === 'section'
    ? t('detailing.sheet.section') : t('detailing.sheet.elevation'));

  /**
   * Focus is captured on open and restored on close by the same helper the 3-D workspace uses.
   *
   * `aria-modal` on a dialog that does not trap focus actively lies to assistive technology — the
   * defect the PR20 plan lists first for the overlay. Not worth reintroducing one panel over.
   */
  $effect(() => {
    if (!sheetOpen) return;
    return captureFocus(sheetDialog);
  });

  function onSheetKeydown(e: KeyboardEvent) {
    if (!sheetOpen) return;
    if (e.key === 'Escape') { sheetOpen = false; return; }
    if (cycleTabWithin(sheetDialog, e)) e.preventDefault();
  }
</script>

<svelte:window onkeydown={onSheetKeydown} />

{#if detailingStore.sheetSvg}
  <figure class="sheet-figure" data-testid="sheet-figure">
    <figcaption class="sheet-caption">
      <span class="sheet-title" data-testid="sheet-caption">
        {assemblyLabel}
        <span class="sheet-kind">
          {kindLabel}
        </span>
      </span>
      <button
        type="button"
        class="sheet-expand"
        data-testid="sheet-expand"
        onclick={() => (sheetOpen = true)}
        title={t('detailing.sheet.expandHint')}
      >⤢ {t('detailing.sheet.expand')}</button>
    </figcaption>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by sheetToSvg, all text escaped -->
    <div class="sheet" data-testid="sheet-preview">{@html detailingStore.sheetSvg}</div>
  </figure>
{:else}
  <p class="sheet-empty" data-testid="sheet-empty">{t('detailing.sheet.empty')}</p>
{/if}

<!--
  The sheet at a size you can read.

  Rendered from the same `detailingStore.sheetSvg` the preview shows — one projection, two
  presentations. `overflow: auto` on the body is the zoom/pan: the SVG keeps its natural size and
  the dialog scrolls, so nothing is scaled down into illegibility and nothing is cropped.
-->
{#if sheetOpen && detailingStore.sheetSvg}
  <div
    class="sheet-modal"
    data-testid="sheet-modal"
    role="dialog"
    aria-modal="true"
    aria-label={t('detailing.sheet.expand')}
    bind:this={sheetDialog}
    tabindex="-1"
  >
    <header>
      <h2>
        {assemblyLabel}
        <span class="kind">
          {kindLabel}
        </span>
        {#if detailingStore.document}
          <span class="rev">{tp('detailing.doc.revision', { n: detailingStore.document.revision.number })}</span>
        {/if}
      </h2>
      <button type="button" data-testid="sheet-modal-close" onclick={() => (sheetOpen = false)}>
        ✕ {t('detailing.sheet.close')}
      </button>
    </header>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by sheetToSvg, all text escaped -->
    <div class="sheet-modal-body" data-testid="sheet-modal-body">{@html detailingStore.sheetSvg}</div>
  </div>
{/if}

<style>
  .sheet-figure { margin: 0.5rem 0; display: flex; flex-direction: column; gap: 0.25rem; }
  .sheet-caption {
    display: flex; align-items: center; justify-content: space-between; gap: 0.5rem;
    font-size: 0.72rem; color: var(--st-text-2);
  }
  .sheet-title { font-weight: 600; color: var(--st-text); }
  .sheet-kind { font-weight: 400; color: var(--st-text-2); }
  .sheet-expand {
    background: var(--st-surface-3); border: 1px solid var(--st-interactive);
    color: var(--st-text); border-radius: 4px; padding: 2px 8px;
    font-size: 0.7rem; cursor: pointer; white-space: nowrap;
  }
  .sheet-expand:hover { background: var(--st-hair-strong); }
  .sheet-expand:focus-visible { outline: 2px solid var(--st-value); outline-offset: 1px; }
  .sheet-empty {
    margin: 0.5rem 0; padding: 0.6rem 0.7rem;
    border: 1px dashed var(--st-hair-strong); border-radius: 4px;
    font-size: 0.75rem; color: var(--st-text-2);
  }
  /* A useful minimum: below this the drawing stops being readable and becomes decoration. */
  .sheet { overflow: auto; background: var(--st-text); border-radius: 4px; min-height: 9rem; }
  .sheet :global(svg) { max-width: 100%; height: auto; display: block; }

  .sheet-modal {
    position: fixed; inset: 0; z-index: 950;
    display: flex; flex-direction: column;
    background: var(--st-bg);
  }
  .sheet-modal header {
    display: flex; align-items: center; justify-content: space-between; gap: 1rem;
    padding: 0.5rem 0.9rem;
    border-bottom: 1px solid var(--st-hair);
    background: var(--st-surface);
  }
  .sheet-modal h2 {
    margin: 0; font-size: 0.9rem; font-weight: 600; color: var(--st-text);
    display: flex; align-items: baseline; gap: 0.5rem;
  }
  .sheet-modal .kind, .sheet-modal .rev { font-size: 0.75rem; font-weight: 400; color: var(--st-text-2); }
  .sheet-modal header button {
    background: var(--st-surface-3); border: 1px solid var(--st-hair-strong);
    color: var(--st-text); border-radius: 4px; padding: 3px 10px;
    font-size: 0.75rem; cursor: pointer;
  }
  .sheet-modal header button:hover { background: var(--st-hair-strong); }
  .sheet-modal header button:focus-visible { outline: 2px solid var(--st-value); outline-offset: 1px; }
  /* The scroll IS the pan: the sheet keeps its own size and the window moves over it. */
  .sheet-modal-body { flex: 1 1 auto; overflow: auto; background: var(--st-text); padding: 0.5rem; }
  .sheet-modal-body :global(svg) { display: block; margin: 0 auto; }
</style>
